# TARGETS

# target: prerequisites
# 	commands


# build is 'just' a name.
# we can give it any name
build:
	echo "running build"
	gcc main.c -o main


# 'make' runs the entire thing, but
# 'make execute' will just run the 'execute'
# target
execute:
	echo "running execute"
	./main

clean:
	echo "running clean"
	rm -f main